# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: ecs-bind
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format: binary
