version: 2.1
orbs:
  slack: circleci/slack@0.1.1
jobs:
  lint:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    environment:
      REPO_NAME: "github.com/yasuharu519/ecs-bind"
      GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      # Get dep cache
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      # Get build cache
      - restore_cache:
          keys:
              - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
          paths:
              - /tmp/go/cache
      - run: golint ./... | tee /dev/tty | xargs -r false
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
              - /go/src/github.com/folio-sec/ecs-deploy/vendor
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
              - /tmp/go/cache
      - slack/notify
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    environment:
      REPO_NAME: "github.com/yasuharu519/ecs-bind"
      GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      # Get build cache
      - restore_cache:
          keys:
              - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
          paths:
              - /tmp/go/cache
      - run: go build
      - slack/notify
workflows:
  version: 2
  build:
    jobs:
      - lint
      - build:
          requires:
            - lint
